---

- name: ActiveMQ Install
  include: "install-{{ ansible_os_family|lower }}.yml"

- name: Create activemq instance config directories
  file:
    path:  "{{ activemq_conf_dir }}/instances-available/{{ item }}"
    state: directory
  with_items: "{{ activemq_instances|map(attribute='name')|list }}"

- name: Create activemq instances config files
  template:
    src:  activemq.xml.j2
    dest: "{{ activemq_conf_dir }}/instances-available/{{ item.name }}/activemq.xml"
  with_items: "{{ activemq_instances }}"
  notify: Restart activemq

- name: Create activemq instances log config files
  template:
    src:  log4j.properties.j2
    dest: "{{ activemq_conf_dir }}/instances-available/{{ item.name }}/log4j.properties"
  with_items: "{{ activemq_instances }}"

- name: Enable activemq instances
  file:
    src:   "{{ activemq_conf_dir }}/instances-available/{{ item.name }}"
    dest:  "{{ activemq_conf_dir }}/instances-enabled/{{ item.name }}"
    owner: root
    group: root
    state: link
  with_items: "{{ activemq_instances }}"
  notify: Restart activemq

- name: Create activemq daemon startup config file
  template:
    src:  etc-default-activemq.j2
    dest: /etc/default/activemq
    mode: 0644

- name: Ensure correct permission for activemq home dir
  file:
    path:  "{{ activemq_home_dir }}"
    owner: "{{ activemq_user }}"
    group: root
    mode:  0755

- name: Start activemq
  service: name=activemq enabled=yes state=started
